#include "login.h"
#include "utils.h"
#include "dashboard.h"
#include "lib/json.hpp"

void loginUser() {
    string username, password;
    cout << "Nhap ten dang nhap: ";
    cin >> username;

    json userData = loadUserCredentials(username);
    if (userData.empty()) {
        cout << "Tai khoan khong ton tai!\n";
        return;
    }

    cout << "Nhap mat khau: ";
    cin >> password;

    if (userData["Password"] == hashPassword(password)) {
        cout << "Dang nhap thanh cong!\n";

        bool isAutoGenerated = userData["isAutoGenerated"].get<bool>();

        // Neu la mat khau tu sinh thi thay doi ngay
        if (isAutoGenerated) {
            string newPassword, confirmNewPassword;

            cin.ignore(); // Xoa bo nho dem truoc khi dung getline()

            do {
                cout << "Mat khau cua ban la mat khau tu dong. Vui long thay doi ngay!\n";
                cout << "Nhap mat khau moi: ";
                getline(cin, newPassword);

                cout << "Nhap lai mat khau moi: ";
                getline(cin, confirmNewPassword);

                if (newPassword != confirmNewPassword) {
                    cout << "Mat khau khong khop, vui long thu lai!\n";
                } else if (newPassword.length() < 6 || newPassword.length() > 64) {
                    cout << "Mat khau phai tu 6-64 ky tu!\n";
                } else {
                    break;
                }

            } while (true);

            // Luu mat khau moi
            userData["Password"] = hashPassword(newPassword);
            userData["isAutoGenerated"] = false; // Bo trang thai tu sinh

            saveUserCredentials(username, hashPassword(newPassword), false);

            cout << "Mat khau thay doi thanh cong, vui long dang nhap lai voi mat khau moi!\n";
        } else {
            // Doc thong tin tu file json
            json userInfo = loadUserInfo(username);
            // Chuyen du lieu vao dashboard sau khi dang nhap thanh cong
            showDashboard(username, userData, userInfo);
        }
    } else {
        cout << "Sai mat khau!\n";
    }
}