#include "register.h"
#include "utils.h"
#include "wallet.h"
#include <regex> // kiem tra dinh dang
#include "sendemail.h"

bool isValidDate(int day, int month, int year) {
    if (year < 1900 || year > 2100) return false; // Gioi han nam

    int daysInMonth[] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

    // Kiem tra nam nhuan
    if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)) {
        daysInMonth[2] = 29;
    }

    // Kiem tra thang & ngay
    return (month >= 1 && month <= 12) && (day >= 1 && day <= daysInMonth[month]);
}

bool isEmailExist(const std::string& email) {
    // Duyệt qua tất cả thư mục con trong thư mục users
    for (const auto& entry : fs::directory_iterator("users")) {
        if (entry.is_directory()) {
            std::string infoFilePath = entry.path().string() + "/info.json";
            
            // Kiểm tra nếu file info.json tồn tại
            if (fs::exists(infoFilePath)) {
                std::ifstream ifs(infoFilePath);
                json userInfo;
                ifs >> userInfo;
                
                // Kiểm tra nếu email trong tệp trùng với email đã nhập
                if (userInfo.contains("Email") && userInfo["Email"] == email) {
                    return true;  // Email đã tồn tại
                }
            }
        }
    }
    return false;  // Email không tồn tại
}

void registerUser() {
    string username, password, confirmPassword;
    json userData;
    
     // Define userDir at the beginning of the function
     std::string userDir = "users/" + username;

    // Ten dang nhap (username)
    do {
        cout << "Nhap ten dang nhap (bat buoc): ";
        cin >> username;

        // Bieu thuc chinh quy kiem tra ten dang nhap hop le
        regex usernamePattern("^[a-zA-Z0-9_.]{4,32}$");

        if (!regex_match(username, usernamePattern)) {
            cout << "Ten dang nhap khong hop le! 4-32 ky tu, chi gom chu, so, dau . hoac _ .\n";
        } else {
            break; // Hop le thi thoat vong lap
        }

    } while (true);

    if (fs::exists("users/" + username + "/settings.json")) {
        cout << "Tai khoan da ton tai! Dang ky that bai.\n";
        return;
    }

    // Nhap va xac nhan mat khau
    bool isAutoGenerated = false;

    // Xoa bo nho dem truoc khi nhap
    cin.ignore(numeric_limits<streamsize>::max(), '\n');

    do {
        cout << "Nhap mat khau (khong nhap se tu dong tao): ";

        getline(cin, password); // Dung getline de nhap ca chuoi rong

        if (password.empty()) {
            password = generateRandomPassword();
            isAutoGenerated = true; // Danh dau mat khau tu sinh
            cout << "Mat khau cua ban la: " << password << endl;
            break;
        }

        cout << "Nhap lai mat khau: ";
        getline(cin, confirmPassword);
        if (password != confirmPassword) {
            cout << "Mat khau khong khop, vui long nhap lai!\n";
        } else if (password.length() < 6 || password.length() > 64) {
            cout << "Mat khau phai tu 6-64 ky tu!\n";
        } else {
            break;
        }

    } while (true);

    string hashedPassword = hashPassword(password);

    // Luu thong tin dang nhap
    saveUserCredentials(username, hashedPassword, isAutoGenerated);

    // Nhap thong tin ca nhan

    // Email
    cout << "Nhap email (bat buoc): ";
    string email;
    regex emailPattern(R"(^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$)"); // Regex kiem tra email

    while (true) {
        getline(cin, email);

        // Kiem tra email hop le
        if (!regex_match(email, emailPattern)) {
            cout << "Email khong hop le! Vui long nhap lai (vi du: example@gmail.com): ";
        } else {
            // Kiểm tra xem email đã tồn tại chưa
            if (isEmailExist(email)) {
                std::cout << "Email da ton tai! Vui long nhap email khac: ";
            } else {
                break;
            }
        }
        

    }

    userData["Email"] = email;
    
    // Ho ten
    cout << "Nhap ho ten (khong bat buoc): ";
    string fullName;
    do {
        getline(cin, fullName);

        // Neu nguoi dung khong nhap gi (nhan Enter), cho phep bo qua
        if (fullName.empty()) {
            break;
        }

        // Bieu thuc chinh quy kiem tra ho ten hop le
        regex fullNamePattern("^[A-Za-zÀ-Ỹà-ỹ\\s]{2,50}$");

        if (!regex_match(fullName, fullNamePattern)) {
            cout << "Ho ten khong hop le! Chi chua chu cai va dau cach, tu 2-50 ky tu.\n";
        } else {
            break; // Hop le thi thoat vong lap
        }

    } while (true);
    userData["FullName"] = fullName;

    // Gioi tinh
    int choice;
    string gender;
    do {
        cout << "Chon gioi tinh (khong bat buoc):\n";
        cout << "1. Nam\n";
        cout << "2. Nu\n";
        cout << "Chon (1/2 hoac Enter de bo qua): ";

        string input;
        getline(cin, input); // Doc ca dong de kiem tra nguoi dung co nhap khong

        if (input.empty()) { 
            gender = ""; // Cho phep bo qua
            break;
        }

        // Kiem tra neu input co dung 1 ky tu va la so 1 hoac 2
        if (input == "1") {
            gender = "Nam";
            break;
        } else if (input == "2") {
            gender = "Nu";
            break;
        } else {
            cout << "Lua chon khong hop le! Vui long nhap 1, 2 hoac Enter de bo qua.\n";
        }

    } while (true);
    userData["Gender"] = gender;

    // Dia chi
    cout << "Nhap dia chi (khong bat buoc): ";
    string address;

    do {
        getline(cin, address);
        
        if (address.length() > 255) {
            cout << "Dia chi khong hop le! Toi da 255 ky tu";
        } else {
            break; // Dia chi hop le, thoat vong lap
        }

    } while (true);
    userData["Address"] = address;

    // Dien thoai
    cout << "Nhap so dien thoai (khong bat buoc): ";
    string phone;
    regex phonePattern("^[0-9]{0,16}$"); // Bieu thuc chinh quy chi cho phep so (tu 1 den 16 ky tu)
    do {
        getline(cin, phone);

        if (!regex_match(phone, phonePattern)) {
            cout << "So dien thoai khong hop le! Chi chua so, toi da 16 ky tu ";
        } else {
            break; // Hop le thi thoat vong lap
        }

    } while (true);
    userData["Phone"] = phone;

    // Ngay sinh
    string birthday;
    regex datePattern(R"(^\d{2}/\d{2}/\d{4}$)"); // Dinh dang dd//mm//yyyy
    do {
        cout << "Nhap ngay sinh (dd/mm/yyyy) (khong bat buoc): ";
        getline(cin, birthday);

        // Neu nguoi dung bam Enter (khong nhap gi), cho phep bo qua
        if (birthday.empty()) {
            break;
        }

        if (!regex_match(birthday, datePattern)) {
            cout << "Dinh dang ngay sinh khong hop le! Vui long nhap lai.\n";
            continue;
        }

        // Tach ngay, thang, nam
        int day, month, year;
        if (sscanf(birthday.c_str(), "%d/%d/%d", &day, &month, &year) != 3) {
            cout << "Dinh dang ngay sinh khong hop le! Vui long nhap lai.\n";
            continue;
        }

        // Kiem tra ngay hop le
        if (!isValidDate(day, month, year)) {
            cout << "Ngay sinh khong hop le! Vui long nhap lai.\n";
        } else {
            break; // Thoat vong lap neu hop le
        }

    } while (true);
    userData["Birthday"] = birthday;

    saveUserInfo(username, userData);

    // Tao vi cho nguoi dung moi
    if (!createWallet(username)) {
        cout << "Loi khi tao vi! Dang ky that bai.\n";
        fs::remove_all("users/" + username);
        return;
    }
    cout << "Da tao vi diem cho tai khoan cua ban.\n";

    // Gui email chao mung
    if (sendRegistrationSuccessEmail(email, username)) {
        cout << "Email thong bao dang ky da duoc gui!\n";
        cout << "Dang ky thanh cong!\n";
    } else {
        cout << "Loi khi gui email dang ky! Dang ky that bai.\n";
        // Xoa thong tin nguoi dung (bao gom ca vi)
        fs::remove_all("users/" + username);
        return;
    }
}